# fly.toml app configuration file generated for wanderer-test on 2024-05-31T22:56:48+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wanderer'
primary_region = 'ams'
kill_signal = 'SIGTERM'
swap_size_mb = 512

[build]

[deploy]
  release_command = '/app/bin/migrate.sh'

[env]
  PHX_HOST = 'wanderer.fly.dev'
  PHX_SERVER = 'true'
  PORT = '8080'

[metrics]
port = 4021
path = "/metrics"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
